version: '3'

services:
    db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: desafio
      networks:
        - nodeapp

    app:
      image: felipealvesprestes/fullcycle-node
      entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
      container_name: app
      networks:
        - nodeapp
      volumes:
        - ./node:/usr/src/app
      tty: true
      command: bash -c "npm install && node index.js"

    nginx:
      image: felipealvesprestes/fullcycle-nginx
      container_name: nginx
      ports:
        - "8080:80"
      volumes:
        - ./nginx:/etc/nginx/conf.d
      networks:
        - nodeapp

networks:
  nodeapp:
